export const REFERENCE_ACTIVE_CAMERA_ID = 0;
export const REFERENCE_JOINT_ROI_CAMERA_ID = 0;
export const REFERENCE_CAMERA_IDS = [0, 1, 2, 3] as const;
export const REFERENCE_BUNDLE_VIEW_CAMERA_IDS = [0, 1, 2, 3] as const;
export const REFERENCE_REQUIRED_CAMERA_IDS = REFERENCE_CAMERA_IDS;
